# Site settings
title: eayoungs data science
email: eayoungs@gmail.com
description:  Adventures in data
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://eayoungs.github.io/" # the base hostname and protocol for your site
github_username:  eayoungs

# Build settings
markdown: kramdown
highlighter: rouge
future: true
